services:
  mongo:
    image: mongodb/atlas
    privileged: true
    volumes:
      - data-cni:/etc/cni
      - data-containers:/var/lib/containers
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    ports:
      - 27017:27017
    env_file:
      - .env
volumes:
  data-cni:
  data-containers: